import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <Providers>
          <main className="dark min-h-screen h-max text-foreground bg-background">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
